"""Add a section reference to assignments

Revision ID: 007eecbeb841
Revises: 9490acc7e3d6
Create Date: 2019-05-22 09:00:35.494424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007eecbeb841'
down_revision = '9490acc7e3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.add_column('assignment', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'section_id')
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='student_pkey'),
    sa.UniqueConstraint('username', name='student_username_key')
    )
    # ### end Alembic commands ###
