"""Add TeacherData

Revision ID: 343369d7da0b
Revises: cf4eaaa818f8
Create Date: 2019-05-19 23:00:06.773742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343369d7da0b'
down_revision = 'cf4eaaa818f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('section_teacher_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'user', ['teacher_id'], ['id'])
    op.add_column('user', sa.Column('teacher_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'teacher_data', ['teacher_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'teacher_data_id')
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'teacher', ['teacher_id'], ['id'])
    op.drop_table('teacher_data')
    # ### end Alembic commands ###
