"""Make section names unique per teacher

Revision ID: 73feecd49844
Revises: e62c33be0003
Create Date: 2019-05-20 11:48:09.912720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73feecd49844'
down_revision = 'e62c33be0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.create_unique_constraint('_name_teacher_id_uc', 'section', ['teacher_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_teacher_id_uc', 'section', type_='unique')
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teacher_pkey'),
    sa.UniqueConstraint('username', name='teacher_username_key')
    )
    # ### end Alembic commands ###
