"""Add maximum size to sections

Revision ID: 94f158be822c
Revises: 73feecd49844
Create Date: 2019-05-20 16:43:47.476863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f158be822c'
down_revision = '73feecd49844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('max_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'max_size')
    # ### end Alembic commands ###
