"""Add `published` field to assignments

Revision ID: a3a3a6c146f1
Revises: 007eecbeb841
Create Date: 2019-05-22 17:57:03.995424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a3a6c146f1'
down_revision = '007eecbeb841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'published')
    # ### end Alembic commands ###
