"""Reference TeacherData, not Teacher, from Section

Revision ID: c29bcb8fbe94
Revises: 343369d7da0b
Create Date: 2019-05-20 11:04:47.566121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29bcb8fbe94'
down_revision = '343369d7da0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_teacher_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'teacher_data', ['teacher_id'], ['id'])
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.create_foreign_key('section_teacher_id_fkey', 'section', 'user', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
